import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");

const bundles = {
  app: [
    "js/page-transition.js",
    "js/supabase-client.js",
    "js/utils.js",
    "js/class-schedule.js",
    "js/auth.js",
    "js/rotations.js",
    "js/notifications.js",
    "js/tasks.js",
    "js/auto-assign.js",
    "js/schedule.js",
    "js/calendar.js",
    "js/dashboard.js",
    "js/members.js",
    "js/shopping.js",
    "js/shopping-ai.js",
    "js/settings.js",
    "js/app.js",
    "js/push-notifications.js",
    "js/theme.js",
    "js/pwa.js",
  ],
  login: ["js/supabase-client.js", "js/auth.js", "js/theme.js"],
  expenses: ["js/page-transition.js", "js/supabase-client.js", "js/auth.js", "js/theme.js"],
};

await mkdir(resolve(root, "src/generated"), { recursive: true });

for (const [name, files] of Object.entries(bundles)) {
  let source = (await Promise.all(files.map((file) => readFile(resolve(root, file), "utf8")))).join("\n\n");
  if (name === "login") source += "\nwindow.login = login; window.supabaseClient = supabaseClient;\n";
  if (name === "expenses") {
    const html = await readFile(resolve(root, "Chi tiêu TTBK.html"), "utf8");
    const inlineScript = html.match(/<script>([\s\S]*?)<\/script>/)?.[1] || "";
    source += `\n${inlineScript}\nObject.assign(window, { updateInitValue, saveInitFund, addExpense, addTransfer, closeEditModal, saveEditExpense, closeEditTransferModal, saveEditTransfer, exportJSON, importJSON, exportPDF, exportCSV, addNewYear, switchYear, openEditModal, deleteExpense, openEditTransferModal, deleteTransfer });\n`;
  }
  const output = `// Generated by scripts/build-legacy.mjs. Do not edit.\nconst source = ${JSON.stringify(source)};\nexport function runLegacy() {\n  new Function(source)();\n}\n`;
  const target = resolve(root, `src/generated/${name}-legacy.js`);
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, output, "utf8");
}